#include "debug.h"
#include "tracers.h"
#include "ppc_dyncom_dec.h"
#include "ppc_exc.h"
#include "ppc_cpu.h"
#include "ppc_dyncom_alu.h"
#include "ppc_dyncom_run.h"
#include "ppc_tools.h"
#include "ppc_mmu.h"

#include "llvm/Instructions.h"
#include <dyncom/dyncom_llvm.h>
#include <dyncom/frontend.h>
#include "dyncom/basicblock.h"
#include "skyeye.h"

#include "ppc_dyncom_debug.h"
ppc_opc_func_t ppc_opc_fdivx_func;
ppc_opc_func_t ppc_opc_fsubx_func;
ppc_opc_func_t ppc_opc_faddx_func;
ppc_opc_func_t ppc_opc_fsqrtx_func;
ppc_opc_func_t ppc_opc_fselx_func;
ppc_opc_func_t ppc_opc_fmulx_func;
ppc_opc_func_t ppc_opc_frsqrtex_func;
ppc_opc_func_t ppc_opc_fmsubx_func;
ppc_opc_func_t ppc_opc_fmaddx_func;
ppc_opc_func_t ppc_opc_fnmsubx_func;
ppc_opc_func_t ppc_opc_fnmaddx_func;
ppc_opc_func_t ppc_opc_fcmpu_func;
ppc_opc_func_t ppc_opc_frspx_func;
ppc_opc_func_t ppc_opc_fctiwx_func;
ppc_opc_func_t ppc_opc_fctiwzx_func;
ppc_opc_func_t ppc_opc_fcmpo_func;
ppc_opc_func_t ppc_opc_mtfsb1x_func;
ppc_opc_func_t ppc_opc_fnegx_func;
ppc_opc_func_t ppc_opc_mcrfs_func;
ppc_opc_func_t ppc_opc_mtfsb0x_func;
ppc_opc_func_t ppc_opc_fmrx_func;
ppc_opc_func_t ppc_opc_mtfsfix_func;
ppc_opc_func_t ppc_opc_fnabsx_func;
ppc_opc_func_t ppc_opc_fabsx_func;
ppc_opc_func_t ppc_opc_mffsx_func;
ppc_opc_func_t ppc_opc_mtfsfx_func;
