# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc
import os
import wx.grid



__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcmainframe(wx.Dialog):
#!XRCED:begin-block:xrcmainframe.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcmainframe.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreDialog()
        self.PreCreate(pre)
        get_resources().LoadOnDialog(pre, parent, "mainframe")
        self.PostCreate(pre)

        # Draw the 5x4 table about mem_bank
        colLabels = ["map", "type", "addr", "size"]
        grid = self.FindWindowById(xrc.XRCID('mem_bank_tab'))
        grid.CreateGrid(6,4)
        for row in range(4):
            grid.SetColLabelValue(row, colLabels[row])
 

        # Define variables for the controls, bind event handlers

        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_arch_box, id=xrc.XRCID('arch_box'))
        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_cpu_box, id=xrc.XRCID('cpu_box'))
        self.Bind(wx.EVT_COMBOBOX, self.OnCombobox_mach_box, id=xrc.XRCID('mach_box'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_load_file_path_button, id=xrc.XRCID('load_file_path_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_reset_button, id=xrc.XRCID('reset_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_save_button, id=xrc.XRCID('save_button'))
        self.Bind(wx.EVT_BUTTON, self.OnButton_exit_button, id=xrc.XRCID('exit_button'))

#!XRCED:begin-block:xrcmainframe.OnCombobox_arch_box
    def OnCombobox_arch_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_arch_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_arch_box        

#!XRCED:begin-block:xrcmainframe.OnCombobox_cpu_box
    def OnCombobox_cpu_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_cpu_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_cpu_box        

#!XRCED:begin-block:xrcmainframe.OnCombobox_mach_box
    def OnCombobox_mach_box(self, evt):
        # Replace with event handler code
        print "OnCombobox_mach_box()"
#!XRCED:end-block:xrcmainframe.OnCombobox_mach_box        

#!XRCED:begin-block:xrcmainframe.OnButton_load_file_path_button
    def OnButton_load_file_path_button(self, evt):
        # Replace with event handler code
       print "OnButton_load_file_path_button()"
       dialog = wx.FileDialog(None, "Choose a file", 
			                  os.getcwd(),"", "All files (*)|*", wx.OPEN)

       if dialog.ShowModal() == wx.ID_OK:
            self.FindWindowById(xrc.XRCID('load_file_path_val')).SetValue(dialog.GetPath())

       dialog.Destroy()

#!XRCED:end-block:xrcmainframe.OnButton_load_file_path_button        

#!XRCED:begin-block:xrcmainframe.OnButton_reset_button
    def OnButton_reset_button(self, evt):
        # Replace with event handler code
        print "OnButton_reset_button()"
		
#!XRCED:end-block:xrcmainframe.OnButton_reset_button        

#!XRCED:begin-block:xrcmainframe.OnButton_save_button
    def OnButton_save_button(self, evt):
        # Replace with event handler code
        print "OnButton_save_button()"
        fp = open('skyeye_tmp.conf', 'w+')

        # Fill the commont about skyeye_tmp.conf
        mach_box = self.FindWindowById(xrc.XRCID('mach_box')).GetValue()
        fp.writelines('#skyeye config file for ' + mach_box + '\n')

        arch_box = self.FindWindowById(xrc.XRCID('arch_box')).GetValue()
        print "arch: %s" % arch_box
        fp.writelines('arch: ' + arch_box + '\n')

        cpu_box = self.FindWindowById(xrc.XRCID('cpu_box')).GetValue()
        print "cpu: %s" % cpu_box
        fp.writelines('cpu: ' + cpu_box + '\n')


        print "mach: %s" % mach_box
        fp.writelines('mach: ' + mach_box + '\n\n')

        fp.writelines('#address space\n')
        grid = self.FindWindowById(xrc.XRCID('mem_bank_tab'))

        # Create a [6,4] array for mem_bank
        mem_bank = [[0 for col in range(4)] for row in range(6)]

        # Derive the value from  table.
        for row in range(6):
            for col in range(4):
                mem_bank[row][col] = grid.GetCellValue(row, col)

        # output the data to skyeye_tmp.conf
        break_flag = False 
        for row in range(6):
            for col in range(4):
                if mem_bank[row][col] == '':
                    break_flag = True
                    break 
            if break_flag == True:
                break_flag = False
                continue
            fp.writelines('mem_bank: map=' + mem_bank[row][0] + ', type=' + mem_bank[row][1] + ', addr=' + mem_bank[row][2] + ', size=' + mem_bank[row][3] + '\n')
        fp.writelines('\n')

        # Fill the uart option
        fp.writelines('uart:mod=term\n\n')

        # Fill the load_file option
        load_file_path_val = self.FindWindowById(xrc.XRCID('load_file_path_val')).GetValue()
        addr_text_val = self.FindWindowById(xrc.XRCID('addr_text_val')).GetValue()
#print "load_file: filename=%s, initrd_start=%s" %(load_file_path_val,addr_text_val)
        fp.writelines('load_file: filename=' + load_file_path_val + ', initrd_start=' + addr_text_val + '\n')

        # Fill the load_addr option
        base_addr_val = self.FindWindowById(xrc.XRCID('base_addr_val')).GetValue()
        mask_val = self.FindWindowById(xrc.XRCID('mask_val')).GetValue()
#print "load_addr: base=%s, mask=%s" %(base_addr_val,mask_val)
        fp.writelines('load_addr: base=' + base_addr_val + ', mask=' + mask_val + '\n')

        fp.close()
#!XRCED:end-block:xrcmainframe.OnButton_save_button        

#!XRCED:begin-block:xrcmainframe.OnButton_exit_button
    def OnButton_exit_button(self, evt):
        # Replace with event handler code
        print "OnButton_exit_button()"
        self.Destroy()
#!XRCED:end-block:xrcmainframe.OnButton_exit_button        




# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    wx.FileSystem.AddHandler(wx.MemoryFSHandler())

    dialogs_xrc = '''\
<?xml version="1.0" ?><resource>
  <object class="wxDialog" name="mainframe">
    <object class="wxBoxSizer">
      <orient>wxVERTICAL</orient>
      <object class="sizeritem">
        <object class="wxBoxSizer">
          <object class="sizeritem">
            <object class="wxStaticText" name="dec_text">
              <label>The option of skyeye</label>
            </object>
            <flag>wxALL|wxEXPAND</flag>
          </object>
          <object class="spacer">
            <size>0,10</size>
          </object>
          <object class="sizeritem">
            <object class="wxStaticBoxSizer">
              <object class="sizeritem">
                <object class="wxFlexGridSizer">
                  <object class="sizeritem">
                    <object class="wxStaticText" name="arch_text">
                      <label>arch:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxHORIZONTAL</orient>
                      <object class="sizeritem">
                        <object class="wxComboBox" name="arch_box">
                          <content>
                            <item>arm</item>
                            <item>powerpc</item>
                            <item>x86</item>
                            <item>mips</item>
                          </content>
                          <value>arm</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="cpu_text">
                      <label>cpu:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <orient>wxHORIZONTAL</orient>
                      <object class="sizeritem">
                        <object class="wxComboBox" name="cpu_box">
                          <content>
                            <item>arm710</item>
                            <item>arm7tdmi</item>
                            <item>arm720t</item>
                            <item>sa1110</item>
                            <item>sa1100</item>
                            <item>arm920t</item>
                            <item>arm926ejs</item>
                            <item>pxa25x</item>
                            <item>pxa27x</item>
                            <item>arm11</item>
                          </content>
                          <value>arm920t</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                      </object>
                    </object>
                    <option>1</option>
                    <flag>wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="mach_text">
                      <label>mach:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <object class="sizeritem">
                        <object class="wxComboBox" name="mach_box">
                          <content>
                            <item>at91rm92</item>
                            <item>pxa_lubbock</item>
                            <item>pxa_mainstone</item>
                            <item>s3c2410x</item>
                            <item>s3c2440</item>
                            <item>s3c6410</item>
                          </content>
                          <value>s3c2410x</value>
                          <style>wxCB_READONLY</style>
                          <XRCED>
                            <events>EVT_COMBOBOX</events>
                          </XRCED>
                        </object>
                        <option>1</option>
                      </object>
                      <orient>wxHORIZONTAL</orient>
                    </object>
                    <option>1</option>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="mem_bank_text">
                      <label>mem_bank:</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxBoxSizer">
                      <object class="sizeritem">
                        <object class="wxGrid" name="mem_bank_tab">
                          <style>wxNO_BORDER</style>
                        </object>
                        <minsize>420,200</minsize>
                      </object>
                      <orient>wxVERTICAL</orient>
                    </object>
                    <flag>wxALL|wxEXPAND|wxADJUST_MINSIZE</flag>
                    <minsize>150</minsize>
                  </object>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="load_file_text">
                      <label>load_file:</label>
                    </object>
                    <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxFlexGridSizer">
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="spacer">
                            <size>45,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="load_file_path_text">
                              <label>path:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="load_file_path_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                          <object class="spacer">
                            <size>5,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxButton" name="load_file_path_button">
                              <label>Browse...</label>
                              <XRCED>
                                <events>EVT_BUTTON</events>
                              </XRCED>
                            </object>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <object class="spacer">
                        <size>20,0</size>
                      </object>
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="addr_text">
                              <label>initrd_start:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="addr_text_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <cols>2</cols>
                      <rows>2</rows>
                    </object>
                  </object>
                  <cols>2</cols>
                  <vgap>5</vgap>
                  <hgap>20</hgap>
                  <growablecols>1</growablecols>
                  <object class="sizeritem">
                    <object class="wxStaticText" name="load_addr_text">
                      <label>load_addr:</label>
                    </object>
                  </object>
                  <object class="sizeritem">
                    <object class="wxFlexGridSizer">
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="spacer">
                            <size>7,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="base_addr_text">
                              <label>base_addr:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="base_addr_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <object class="spacer">
                        <size>20,0</size>
                      </object>
                      <object class="sizeritem">
                        <object class="wxBoxSizer">
                          <orient>wxHORIZONTAL</orient>
                          <object class="spacer">
                            <size>42,0</size>
                          </object>
                          <object class="sizeritem">
                            <object class="wxStaticText" name="mask_text">
                              <label>mask:</label>
                            </object>
                            <flag>wxALL|wxALIGN_CENTRE_VERTICAL</flag>
                          </object>
                          <object class="sizeritem">
                            <object class="wxTextCtrl" name="mask_val"/>
                            <flag>wxALL|wxEXPAND|wxALIGN_CENTRE_VERTICAL</flag>
                            <minsize>210, -1</minsize>
                          </object>
                        </object>
                        <option>1</option>
                      </object>
                      <cols>2</cols>
                      <rows>2</rows>
                    </object>
                  </object>
                </object>
                <option>1</option>
                <flag>wxALL|wxEXPAND</flag>
              </object>
              <label>Options:</label>
              <orient>wxVERTICAL</orient>
            </object>
            <flag>wxALL|wxEXPAND</flag>
            <minsize>1000,800</minsize>
          </object>
          <object class="spacer">
            <size>0,10</size>
          </object>
          <object class="sizeritem">
            <object class="wxBoxSizer">
              <orient>wxHORIZONTAL</orient>
              <object class="sizeritem">
                <object class="wxGridSizer">
                  <cols>3</cols>
                  <object class="sizeritem">
                    <object class="wxButton" name="reset_button">
                      <label>reset</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxEXPAND</flag>
                  </object>
                  <hgap>5</hgap>
                  <object class="sizeritem">
                    <object class="wxButton" name="save_button">
                      <label>save</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxEXPAND</flag>
                  </object>
                  <object class="sizeritem">
                    <object class="wxButton" name="exit_button">
                      <label>Quit</label>
                      <XRCED>
                        <events>EVT_BUTTON</events>
                      </XRCED>
                    </object>
                    <flag>wxALL|wxEXPAND</flag>
                  </object>
                </object>
              </object>
            </object>
            <flag>wxALIGN_RIGHT</flag>
          </object>
          <orient>wxVERTICAL</orient>
        </object>
        <option>1</option>
        <flag>wxALL|wxEXPAND</flag>
      </object>
    </object>
    <title>skyeye.conf</title>
    <font>
      <size>11</size>
      <style>normal</style>
      <weight>normal</weight>
      <underlined>0</underlined>
      <family>default</family>
      <face>Ubuntu</face>
      <encoding>UTF-8</encoding>
    </font>
    <style>wxCAPTION|wxRESIZE_BORDER|wxRESIZE_BOX|wxCLOSE_BOX|wxMAXIMIZE_BOX</style>
  </object>
</resource>'''

    wx.MemoryFSHandler.AddFile('XRC/dialogs/dialogs_xrc', dialogs_xrc)
    __res.Load('memory:XRC/dialogs/dialogs_xrc')


# ----------------------- Gettext strings ---------------------

def __gettext_strings():
    # This is a dummy function that lists all the strings that are used in
    # the XRC file in the _("a string") format to be recognized by GNU
    # gettext utilities (specificaly the xgettext utility) and the
    # mki18n.py script.  For more information see:
    # http://wiki.wxpython.org/index.cgi/Internationalization 
    
    def _(str): pass
    
    _("The option of skyeye")
    _("arch:")
    _("arm")
    _("powerpc")
    _("x86")
    _("mips")
    _("arm")
    _("cpu:")
    _("arm710")
    _("arm7tdmi")
    _("arm720t")
    _("sa1110")
    _("sa1100")
    _("arm920t")
    _("arm926ejs")
    _("pxa25x")
    _("pxa27x")
    _("arm11")
    _("arm920t")
    _("mach:")
    _("at91rm92")
    _("pxa&lubbock")
    _("pxa&mainstone")
    _("s3c2410x")
    _("s3c2440")
    _("s3c6410")
    _("s3c2410x")
    _("mem&bank:")
    _("load&file:")
    _("path:")
    _("Browse...")
    _("initrd&start:")
    _("load&addr:")
    _("base&addr:")
    _("mask:")
    _("Options:")
    _("reset")
    _("save")
    _("Quit")
    _("skyeye.conf")

